<script setup lang="ts">
/**
 * Copyright 2026 SciLoop contributors
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * 研究构想 · **工作区**（某个研究任务的界面）。
 *
 * 2026-09-26 研究者口径：打开「研究构想」先看到的是**任务列表**（`IdeasHomeView`），
 * 选一个任务才进到这里。所以本页不再有"选论文"这一步 —— 论文由任务（聚合）决定。
 *
 * 界面口径（同日逐条确认，演示稿 `preview/ideas-demo.html` 定稿）
 * -----------------------------------------------------------------
 * - **四个方向固定**：方法迭代型 / 场景迁移型 / 技术融合型 / 范式拓展型，一次各出 1 条；
 *   对某个方向不满意就「再生成一批」，同方向的产出成为**备选 A/B/C**；
 * - **可行性分析七个维度**：0–100 分（**越高越好**）+ 模型生成的约 50 字分析，
 *   默认全部展开，**研究者不能修改**（这是模型固定生成的结论）；
 * - 界面上**不写解释性小字**（状态用标签、口径用 tooltip）；**不用星级**，难度与评分都是数值。
 */
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { writeDenied } from '@/utils/messages'

import {
  createFeasibility,
  generateIdeas,
  getAggregation,
  getFeasibilityByIdea,
  IDEA_DIRECTIONS,
  listIdeas,
  MECHANISM_DIFFICULTY,
  MECHANISM_LABELS,
  MECHANISM_LAYERS,
  REVIEW_DIMENSIONS,
  type Feasibility,
  type Idea,
  type IdeaMechanism,
} from '@/api/idea'
import { searchPapers, type PaperSearchItem } from '@/api/papers'

const route = useRoute()
const router = useRouter()

const aggregationId = computed(() => {
  const raw = route.params.aggregationId
  const value = Number(Array.isArray(raw) ? raw[0] : raw)
  return Number.isFinite(value) && value > 0 ? value : null
})

const paperIds = ref<number[]>([])
const titleById = ref<Record<number, string>>({})
const ideas = ref<Idea[]>([])
const activeDirection = ref<IdeaMechanism>('refinement')
const activeIdeaId = ref<number | null>(null)

const feasibility = ref<Feasibility | null>(null)
const scoresByDirection = ref<Record<string, number | null>>({})

const loading = ref(false)
const busy = ref('')
const notice = ref('')
/** 本页已经自动补过一次生成，避免来回打转 */
const autoGenerated = ref(false)

/**
 * 每个方向的可行性分析状态（2026-09-26 研究者反馈："分析了很久也没有结果，也没有提示"）。
 * 一次真实分析要十几秒，界面必须**说清在算什么、已经算了多久**，而不是只留一句"正在分析…"。
 */
const analysisState = ref<Record<string, 'idle' | 'running' | 'done' | 'failed'>>({})
const analysisStartedAt = ref(0)
const elapsedSeconds = ref(0)
let elapsedTimer: ReturnType<typeof setInterval> | null = null

/**
 * 正在生成的方向（``''`` / ``'all'`` / 某个方向 key）。
 *
 * ⚠️ **必须与 ``busy`` 分开**：``busy`` 会被可行性分析的 ``finally`` 清空，
 * 两者共用一个变量时，"再生成一批"的进行态会被分析结束顺手抹掉 ——
 * 表现就是**点了按钮看着像没反应**（2026-09-26 研究者实测反馈）。
 */
const generating = ref('')

const DIRECTIONS = IDEA_DIRECTIONS.map((key, index) => ({
  key,
  idx: '①②③④'[index],
  label: MECHANISM_LABELS[key] ?? key,
  layer: MECHANISM_LAYERS[key] ?? '',
  difficulty: MECHANISM_DIFFICULTY[key] ?? 0,
}))

const inputMode = computed(() =>
  paperIds.value.length >= 2 ? '多篇交叉聚合' : paperIds.value.length === 1 ? '单篇精读发散' : '',
)
const paperTags = computed(() =>
  paperIds.value.map((id) => ({
    id,
    label: `#${id} · ${shortTitle(titleById.value[id]) || '（标题未在本页范围内）'}`,
  })),
)

function variantsOf(key: IdeaMechanism): Idea[] {
  return ideas.value
    .filter((idea) => idea.mechanism === key)
    .slice()
    .sort((left, right) => right.id - left.id)
}
const activeVariants = computed(() => variantsOf(activeDirection.value))
const activeIdea = computed(
  () =>
    activeVariants.value.find((idea) => idea.id === activeIdeaId.value) ??
    activeVariants.value[0] ??
    null,
)
const activeMeta = computed(
  () => DIRECTIONS.find((item) => item.key === activeDirection.value) ?? DIRECTIONS[0],
)

const dimensionRows = computed(() => {
  const rows = feasibility.value?.dimensions ?? []
  return REVIEW_DIMENSIONS.map((key) => {
    const found = rows.find((item) => item.key === key)
    return {
      key,
      label: found?.label ?? key,
      score: found?.score ?? null,
      analysis: found?.analysis ?? '',
    }
  })
})
const totalScore = computed(() => {
  const value = feasibility.value?.total_score
  return typeof value === 'number' ? Math.round(value) : null
})

function scoreClass(score: number | null): string {
  if (score === null) return ''
  if (score >= 75) return 'dim__score--high'
  if (score >= 50) return 'dim__score--mid'
  return 'dim__score--low'
}

// ---- 分析进度提示（2026-09-26）-------------------------------------------------- #
function startAnalysisClock(): void {
  analysisStartedAt.value = Date.now()
  elapsedSeconds.value = 0
  if (elapsedTimer !== null) clearInterval(elapsedTimer)
  elapsedTimer = setInterval(() => {
    elapsedSeconds.value = Math.round((Date.now() - analysisStartedAt.value) / 1000)
  }, 1000)
}

function stopAnalysisClock(): void {
  if (elapsedTimer !== null) {
    clearInterval(elapsedTimer)
    elapsedTimer = null
  }
}

function setAnalysis(key: IdeaMechanism, state: 'idle' | 'running' | 'done' | 'failed'): void {
  analysisState.value = { ...analysisState.value, [key]: state }
}

/** 一句话进度：正在算哪几个方向、已完成几个（缺了这句，研究者只能干等） */
const analysisProgressText = computed(() => {
  const running = DIRECTIONS.filter((item) => analysisState.value[item.key] === 'running')
  if (running.length === 0) return ''
  const done = DIRECTIONS.filter((item) => analysisState.value[item.key] === 'done').length
  return `正在分析 ${running.map((item) => `${item.idx} ${item.label}`).join('、')}（已完成 ${done}/4 个方向）`
})

function cardStateText(key: IdeaMechanism): string {
  const state = analysisState.value[key]
  if (state === 'running') return '分析中'
  if (state === 'done') return '已分析'
  if (state === 'failed') return '分析失败'
  return ''
}

function shortTitle(title: string | null | undefined): string {
  const value = title ?? ''
  return value.length > 34 ? `${value.slice(0, 34)}…` : value
}

function ownerHint(error: unknown): string {
  const status = (error as { status?: number })?.status
  if (status === 403) return writeDenied('生成研究构想')
  return error instanceof Error ? error.message : String(error)
}

// ---- 加载 ----
async function loadTask(): Promise<void> {
  if (aggregationId.value === null) {
    notice.value = '没有指定研究任务'
    return
  }
  loading.value = true
  notice.value = ''
  try {
    const aggregation = await getAggregation(aggregationId.value)
    paperIds.value = aggregation.paper_ids ?? []
    const page = await listIdeas({ aggregationId: aggregationId.value, pageSize: 100 })
    ideas.value = page.items ?? []
    const first = variantsOf(activeDirection.value)[0]
    activeIdeaId.value = first?.id ?? null
    // 任务刚建好、还没生成过 → 自动补一次四个方向（省掉一次点击）
    if (ideas.value.length === 0 && !autoGenerated.value) {
      autoGenerated.value = true
      await runGenerate([...IDEA_DIRECTIONS])
    } else if (activeIdea.value) {
      // 已经有 idea → 直接把当前方向的分析拉出来（库里没有就现算）
      await loadFeasibility()
    }
  } catch (error) {
    notice.value = ownerHint(error)
  } finally {
    loading.value = false
  }
}

async function loadPaperTitles(): Promise<void> {
  try {
    const page = await searchPapers({ pageSize: 100 })
    titleById.value = Object.fromEntries((page.items ?? []).map((item: PaperSearchItem) => [item.id, item.title]))
  } catch {
    titleById.value = {}
  }
}

async function refreshIdeas(): Promise<void> {
  if (aggregationId.value === null) return
  const page = await listIdeas({ aggregationId: aggregationId.value, pageSize: 100 })
  ideas.value = page.items ?? []
}

// ---- 生成 ----
async function runGenerate(directions: IdeaMechanism[]): Promise<void> {
  if (aggregationId.value === null) return
  generating.value = directions.length === 1 ? directions[0] : 'all'
  notice.value = ''
  try {
    const result = await generateIdeas({
      aggregation_id: aggregationId.value,
      directions,
      count: 1,
      mode: 'auto',
    })
    await refreshIdeas()
    const first = variantsOf(activeDirection.value)[0]
    activeIdeaId.value = first?.id ?? null
    if (result.generated_count === 0) {
      notice.value = '这次没有产出可用的 idea：素材里没有足够的证据支撑，换一批论文或稍后重试。'
      return
    }
    void collectScores(directions)
  } catch (error) {
    notice.value = ownerHint(error)
  } finally {
    generating.value = ''
  }
}

/** 后台为这些方向各算一次可行性（界面按需拿分，不让用户等） */
async function collectScores(directions: IdeaMechanism[]): Promise<void> {
  if (directions.length === 0) return
  startAnalysisClock()
  await Promise.all(
    directions.map(async (key) => {
      const idea = variantsOf(key)[0]
      if (!idea) return
      setAnalysis(key, 'running')
      try {
        // **先查有没有算过**：已有报告就直接复用 —— 一次真实分析要调模型十几秒，
        // 重复算既慢又费钱（研究者的反馈就是"分析了很久也没有结果"）。
        const existing = await getFeasibilityByIdea(idea.id).catch(() => null)
        const report =
          existing && (existing.dimensions?.length ?? 0) > 0
            ? existing
            : await createFeasibility({ idea_id: idea.id, use_llm: true })
        scoresByDirection.value = { ...scoresByDirection.value, [key]: Math.round(report.total_score) }
        setAnalysis(key, 'done')
      } catch {
        scoresByDirection.value = { ...scoresByDirection.value, [key]: null }
        setAnalysis(key, 'failed')
      }
    }),
  )
  stopAnalysisClock()
  // 当前正在看的方向如果有分数了，顺带把详情刷出来
  if (scoresByDirection.value[activeDirection.value] !== null) await loadFeasibility()
}

// ---- 选择方向与备选 ----
async function selectDirection(key: IdeaMechanism): Promise<void> {
  activeDirection.value = key
  activeIdeaId.value = variantsOf(key)[0]?.id ?? null
  await loadFeasibility()
}

async function selectVariant(id: number): Promise<void> {
  activeIdeaId.value = id
  await loadFeasibility()
}

async function loadFeasibility(): Promise<void> {
  feasibility.value = null
  const idea = activeIdea.value
  if (!idea) return
  const dir = activeDirection.value
  busy.value = 'feasibility'
  try {
    const existing = await getFeasibilityByIdea(idea.id)
    // 已经有报告就直接用（`dimensions` 为空说明那只是条占位记录，不算数）
    if (existing && (existing.dimensions?.length ?? 0) > 0) {
      feasibility.value = existing
      scoresByDirection.value = { ...scoresByDirection.value, [dir]: Math.round(existing.total_score) }
      setAnalysis(dir, 'done')
      return
    }
  } catch {
    /* 还没有历史报告 → 往下走，现算一次 */
  }
  // 现算：真实模型要十几秒，必须把「在算什么、算了多久」显示出来
  setAnalysis(dir, 'running')
  startAnalysisClock()
  try {
    // 进到工作区就该看到分析，不该让研究者自己再点一次「做可行性分析」
    const report = await createFeasibility({ idea_id: idea.id, use_llm: true })
    feasibility.value = report
    scoresByDirection.value = { ...scoresByDirection.value, [dir]: Math.round(report.total_score) }
    setAnalysis(dir, 'done')
  } catch (error) {
    notice.value = ownerHint(error)
    feasibility.value = null
    setAnalysis(dir, 'failed')
  } finally {
    stopAnalysisClock()
    busy.value = ''
  }
}

function backToList(): void {
  void router.push('/ideas')
}

onMounted(async () => {
  await Promise.all([loadPaperTitles(), loadTask()])
})

onUnmounted(() => {
  stopAnalysisClock()
})

watch(aggregationId, () => {
  autoGenerated.value = false
  ideas.value = []
  feasibility.value = null
  scoresByDirection.value = {}
  void loadTask()
})
</script>

<template>
  <section class="ideas">
    <header class="ideas__head">
      <button class="link-btn" type="button" @click="backToList">← 研究构想</button>
      <h1>任务 #{{ aggregationId ?? '—' }}</h1>
      <span class="spacer" />
      <button
        class="btn btn--primary"
        type="button"
        :disabled="generating === 'all' || aggregationId === null"
        @click="runGenerate([...IDEA_DIRECTIONS])"
      >
        {{ generating === 'all' ? '生成中…' : '生成 4 个方向' }}
      </button>
    </header>

    <!-- 生成中：真实模型要读完素材再写，二三十秒；缺了这句就像"点了没反应" -->
    <p v-if="generating" class="progress">
      <span class="progress__dot" />
      {{
        generating === 'all'
          ? '正在生成四个方向的新方案'
          : `正在为「${activeMeta.idx} ${activeMeta.label}」生成新方案`
      }}…通常 20–30 秒
    </p>
    <!-- 分析进行中：说清"在算什么、算了多久"（原来只有一句"正在分析…"，看不出有没有在动） -->
    <p v-else-if="analysisProgressText" class="progress">
      <span class="progress__dot" />
      {{ analysisProgressText }} · 已用 {{ elapsedSeconds }} 秒
    </p>
    <p v-else-if="notice" class="notice">{{ notice }}</p>

    <article class="panel">
      <header class="panel__head">
        <h2>输入</h2>
      </header>
      <div v-if="loading" class="empty">正在加载…</div>
      <div v-else class="row">
        <span v-if="inputMode" class="tag tag--brand">{{ inputMode }}</span>
        <span v-for="paper in paperTags" :key="paper.id" class="tag">{{ paper.label }}</span>
      </div>
    </article>

    <article class="panel">
      <header class="panel__head">
        <h2>四个创新方向</h2>
      </header>
      <div class="dircards">
        <button
          v-for="item in DIRECTIONS"
          :key="item.key"
          class="dircard"
          :class="{ 'is-on': item.key === activeDirection }"
          type="button"
          @click="selectDirection(item.key)"
        >
          <span class="dircard__top">
            <span class="dircard__name">{{ item.idx }} {{ item.label }}</span>
            <span class="dircard__score">{{ scoresByDirection[item.key] ?? '—' }}</span>
          </span>
          <span class="dircard__meta">
            难度 {{ item.difficulty }} · {{ item.layer }} · {{ variantsOf(item.key).length }} 个备选
            <span v-if="cardStateText(item.key)" class="dircard__state">
              {{ cardStateText(item.key) }}
            </span>
          </span>
          <span class="dircard__brief">{{ variantsOf(item.key)[0]?.title ?? '尚未生成' }}</span>
        </button>
      </div>
    </article>

    <article v-if="activeIdea" class="panel">
      <header class="panel__head">
        <h2>{{ activeMeta.idx }} {{ activeMeta.label }}</h2>
        <span class="tag">{{ activeMeta.layer }}</span>
        <span class="tag">难度 {{ activeMeta.difficulty }}</span>
        <span class="spacer" />
        <button
          class="link-btn"
          type="button"
          :disabled="generating === activeDirection"
          @click="runGenerate([activeDirection])"
        >
          {{ generating === activeDirection ? '生成中…' : '再生成一批' }}
        </button>
      </header>

      <div v-if="activeVariants.length > 1" class="segmented">
        <button
          v-for="(variant, index) in activeVariants"
          :key="variant.id"
          class="segmented__item"
          :class="{ 'is-on': variant.id === activeIdea.id }"
          type="button"
          @click="selectVariant(variant.id)"
        >
          备选 {{ 'ABCDEF'[index] }}
        </button>
      </div>

      <h3 class="idea__title">{{ activeIdea.title }}</h3>
      <p class="idea__content">{{ activeIdea.content }}</p>
      <p v-if="activeIdea.novelty_note" class="idea__note">{{ activeIdea.novelty_note }}</p>

      <header class="panel__head panel__head--sub">
        <h2>可行性分析</h2>
        <span class="spacer" />
        <span class="total">{{ totalScore ?? '—' }}</span>
      </header>

      <p v-if="busy === 'feasibility'" class="empty">
        正在分析「{{ activeMeta.idx }} {{ activeMeta.label }}」的可行性…已用 {{ elapsedSeconds }} 秒
        （每个方向通常十几秒，四个方向会并行算）
      </p>
      <div v-else-if="!feasibility" class="empty">
        这个方向还没有做可行性分析（点其它方向卡可以切换，后台会接着算）。
      </div>
      <div v-else class="dims">
        <div v-for="row in dimensionRows" :key="row.key" class="dim">
          <span class="dim__name">{{ row.label }}</span>
          <span class="dim__score" :class="scoreClass(row.score)">{{ row.score ?? '—' }}</span>
          <span class="dim__text">{{ row.analysis }}</span>
        </div>
      </div>
    </article>
  </section>
</template>

<style scoped>
.ideas {
  padding: var(--space-4);
  display: flex;
  flex-direction: column;
  gap: var(--space-3);
}
.ideas__head {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  flex-wrap: wrap;
}
.ideas__head h1 {
  margin: 0;
  font-size: var(--font-size-lg);
}
.spacer {
  flex: 1;
}
.panel {
  padding: var(--space-4);
  background: var(--color-card-bg);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-lg);
  display: flex;
  flex-direction: column;
  gap: var(--space-3);
}
.panel__head {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  flex-wrap: wrap;
  margin: 0;
}
.panel__head--sub {
  margin-top: var(--space-2);
}
.panel__head h2 {
  margin: 0;
  font-size: var(--font-size-lg);
}
.row {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  flex-wrap: wrap;
}

/* 四个方向卡 */
.dircards {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  gap: var(--space-2);
}
.dircard {
  display: flex;
  flex-direction: column;
  gap: 5px;
  padding: 12px 14px;
  text-align: left;
  cursor: pointer;
  background: var(--color-bg-subtle);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  color: inherit;
  font: inherit;
  transition: border-color 160ms, background-color 160ms;
}
.dircard:hover {
  border-color: var(--color-border-strong);
}
.dircard.is-on {
  border-color: var(--color-brand);
  background: var(--color-brand-soft);
  box-shadow: inset 2px 0 0 var(--color-brand);
}
.dircard__top {
  display: flex;
  align-items: baseline;
  gap: var(--space-2);
}
.dircard__name {
  font-size: var(--font-size-sm);
  font-weight: 600;
}
.dircard__score {
  margin-left: auto;
  font-size: var(--font-size-lg);
  font-weight: 600;
  color: var(--color-brand);
}
.dircard__meta {
  font-size: var(--font-size-xs);
  color: var(--color-text-secondary);
}
.dircard__brief {
  font-size: var(--font-size-xs);
  color: var(--color-text-secondary);
  line-height: 1.6;
}

/* 备选切换 */
.segmented {
  display: inline-flex;
  gap: 2px;
  padding: 2px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  background: var(--color-bg-subtle);
  align-self: flex-start;
}
.segmented__item {
  padding: 4px 12px;
  border: 0;
  border-radius: var(--radius-sm);
  background: transparent;
  color: var(--color-text-secondary);
  font: inherit;
  font-size: var(--font-size-xs);
  cursor: pointer;
}
.segmented__item.is-on {
  background: var(--color-card-bg);
  color: var(--color-text-primary);
  font-weight: 500;
}

/* idea 正文 */
.idea__title {
  margin: 0;
  font-size: var(--font-size-md);
  font-weight: 600;
}
.idea__content {
  margin: 0;
  font-size: var(--font-size-sm);
  line-height: 1.75;
  color: var(--color-text-secondary);
  white-space: pre-wrap;
}
.idea__note {
  margin: 0;
  padding-top: var(--space-2);
  border-top: 1px dashed var(--color-border);
  font-size: var(--font-size-xs);
  line-height: 1.7;
  color: var(--color-text-secondary);
}

/* 可行性分析：每维 0–100 分 + 约 50 字固定分析（只读） */
.total {
  font-size: 20px;
  font-weight: 600;
  color: var(--color-brand);
}
.dims {
  display: flex;
  flex-direction: column;
}
.dim {
  display: grid;
  grid-template-columns: 118px 54px minmax(0, 1fr);
  gap: 14px;
  align-items: baseline;
  padding: 11px 2px;
  border-bottom: 1px solid var(--color-border);
}
.dim:last-child {
  border-bottom: 0;
}
.dim__name {
  font-size: var(--font-size-sm);
}
.dim__score {
  font-size: var(--font-size-md);
  font-weight: 600;
  text-align: right;
}
.dim__score--high {
  color: var(--color-success);
}
.dim__score--mid {
  color: var(--color-warning);
}
.dim__score--low {
  color: var(--color-danger);
}
.dim__text {
  font-size: var(--font-size-sm);
  line-height: 1.75;
  color: var(--color-text-secondary);
}
/* 分析进行中的进度条：带一个呼吸的点，让人看出"确实在动" */
.progress {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  margin: 0;
  padding: 9px 14px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius-md);
  background: var(--color-brand-soft);
  font-size: var(--font-size-sm);
  color: var(--color-text-primary);
}
.progress__dot {
  width: 8px;
  height: 8px;
  border-radius: 999px;
  background: var(--color-brand);
  animation: progress-pulse 1.1s ease-in-out infinite;
}
@keyframes progress-pulse {
  0%,
  100% {
    opacity: 1;
    transform: scale(1);
  }
  50% {
    opacity: 0.35;
    transform: scale(0.72);
  }
}
.dircard__state {
  margin-left: 6px;
  padding: 1px 7px;
  border-radius: 999px;
  background: var(--color-brand-soft);
  color: var(--color-brand);
  font-size: 11px;
}
.empty {
  margin: 0;
  padding: var(--space-4) 0;
  text-align: center;
  color: var(--color-text-secondary);
  font-size: var(--font-size-sm);
}
@media (max-width: 900px) {
  .dim {
    grid-template-columns: 100px 46px minmax(0, 1fr);
    gap: 10px;
  }
}
</style>
